export const INDIAN_ENTITY_TYPES = [
  'Private Limited Company',
  'Sole Proprietorship',
  'Partnership Firm (Registered)',
  'Partnership Firm (Unregistered)',
  'Limited Liability Partnership (LLP)',
  'One Person Company (OPC)',
  'Public Limited Company',
  'Section 8 Company (Non-Profit)',
  'Producer Company',
  'Joint Venture Entity',
  'Branch Office (Foreign Entity)',
  'Liaison Office',
  'Project Office',
  'Sole Proprietorship with GST',
  'Unlimited Company',
  'Nidhi Company',
  'Non-Banking Financial Company (NBFC)',
  'Co-operative Society',
  'Trust',
  'Society (Societies Registration Act)',
  'Hindu Undivided Family (HUF)',
  'Foreign Subsidiary Company',
  'Wholly Owned Subsidiary (WOS)',
  'Start-up Entity (DPIIT Recognized)',
  'Micro / Small Enterprise (MSME Entity)'
] as const;

export const INDUSTRY_SECTORS = [
  'Manufacturing & Heavy Engineering',
  'Information Technology & Software',
  'Retail, Wholesale & Trade',
  'Healthcare, Pharmaceuticals & Biotech',
  'Real Estate, Infrastructure & Construction',
  'Agriculture, Farming & Agri-Tech',
  'Textile, Apparel & Garments',
  'FMCG & Consumer Goods',
  'Logistics, Warehousing & Freight',
  'Financial Services, Banking & Fintech',
  'Education, Training & EdTech',
  'Hospitality, Restaurants & Tourism',
  'Renewable Energy, Solar & Utilities',
  'Automotive, EV & Ancillaries',
  'Chemicals, Petrochemicals & Plastics',
  'Media, Advertising & Entertainment',
  'Defence, Aerospace & Electronics',
  'Mining, Metals & Minerals',
  'Telecommunications & Networking',
  'Food Processing & Beverages',
  'Professional, Legal & Consulting Services',
  'Beauty, Personal Care & Wellness',
  'Import, Export & International Trade',
  'Electricals, Power & Hardware',
  'E-Commerce & D2C Brands'
] as const;
